language: rust
sudo: false
dist: trusty
rust:
- 1.22.1
- stable
- beta
- nightly

# Install travis-cargo which sets `--feature unstable` for nightly builds automatically
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only stable build -- --no-default-features --features fork &&
      travis-cargo --only nightly build -- --no-default-features --features "alloc nightly" &&
      (cd test-persistence-location && ./run-tests.sh)

cache: cargo
