[package]
name = "proptest"
version = "0.8.7"
authors = ["Jason Lingle"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/altsysrq/proptest"
documentation = "https://altsysrq.github.io/rustdoc/proptest/0.8.7/proptest/"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]

description = """
Hypothesis-like property-based testing and shrinking.
"""

[badges]
travis-ci = { repository = "AltSysrq/proptest" }

[badges.appveyor]
repository = "AltSysrq/proptest"
branch = "master"
service = "github"

[features]

default = ["std", "fork", "timeout", "bit-set"]

# Enables unstable features of Rust.
unstable = ["rand/i128_support"]

# Required for no_std usage thanks to lazy_static's
# dependency on the spin crate, which is nightly-only
# for no_std.
nightly = ["lazy_static/spin_no_std"]

# Enables the use of standard-library dependent feature
std = ["rand/std", "byteorder/std",
       "quick-error", "regex-syntax", "num-traits/std"]

# For use in no_std environments with access to an allocator
#alloc = ["hashmap_core"]
alloc = []

# Enables use of the "fork" feature.
#
# Requires std.
fork = ["std", "rusty-fork", "tempfile"]

# Enables use of the "timeout" feature.
#
# Requires the "fork" feature.
timeout = ["fork", "rusty-fork/timeout"]

[dependencies]
bitflags = "1.0.1"

# [dependencies.hashmap_core]
# version = "0.1.5"
# optional = true

[dependencies.lazy_static]
version = "1.0.0"
default-features = false

[dependencies.num-traits]
version = "0.2.2"
default-features = false

[dependencies.quick-error]
version = "1.2.1"
optional = true

[dependencies.regex-syntax]
# If you change this, make sure to also bump the `regex` dependency to a
# version that also uses this version of regex-syntax.
version = "0.6.0"
optional = true

[dependencies.bit-set]
version = "0.5.0"
# It doesn't currently work with no_std
# default-features = false
optional = true

[dependencies.rand]
version = "0.5.0"
default-features = false
features = ["alloc", "i128_support"]

[dependencies.byteorder]
version = "1.2.3"
default-features = false

[dependencies.rusty-fork]
version = "0.2.1"
optional = true
default-features = false

[dependencies.tempfile]
version = "3.0"
optional = true

[dev-dependencies]
regex = "1.0"
